
package com.example.lab4rs.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-17T02:41:24.292+03:00
 * Generated source version: 4.0.3
 *
 */
public final class AdditionalWSI_AdditionalPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.lab4ws.soa.com/", "AdditionalService");

    private AdditionalWSI_AdditionalPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AdditionalService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AdditionalService ss = new AdditionalService(wsdlURL, SERVICE_NAME);
        AdditionalWSI port = ss.getAdditionalPort();

        {
        System.out.println("Invoking countTransferred...");
        com.example.lab4rs.client.CountTransferred _countTransferred_parameters = new com.example.lab4rs.client.CountTransferred();
        com.example.lab4rs.client.CountTransferredResponse _countTransferred__return = port.countTransferred(_countTransferred_parameters);
        System.out.println("countTransferred.result=" + _countTransferred__return);


        }

        System.exit(0);
    }

}
