package com.example.lab4rs.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-02-17T02:41:24.353+03:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://service.lab4ws.soa.com/", name = "AdditionalWSI")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AdditionalWSI {

    @WebMethod
    @WebResult(name = "countTransferredResponse", targetNamespace = "http://service.lab4ws.soa.com/", partName = "parameters")
    public CountTransferredResponse countTransferred(

        @WebParam(partName = "parameters", name = "countTransferred", targetNamespace = "http://service.lab4ws.soa.com/")
        CountTransferred parameters
    );
}
